# Generated by Django 2.2.1 on 2019-06-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='user',
        ),
        migrations.AlterField(
            model_name='shoe',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='color',
            field=models.CharField(max_length=20, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.IntegerField(verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
