# Generated by Django 2.2.1 on 2019-06-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190602_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='brand',
            field=models.CharField(max_length=20, verbose_name='Marca'),
        ),
    ]
